### PR TITLE
Change build directory and fix issue #59 

### PR DESCRIPTION
**Pull request by BenoitAnastay**
Edit : I also fixed https://github.com/adafruit/travis-ci-arduino/issues/59

I was trying to use deploy with travis and after a debug I realised that the files are accessible throught shell but not for deploy

Example of a working deploy, 
```
deploy:
  provider: releases
  api_key:
    secure: KEY
  file: "$ARDUINO_HEX_DIR/esp8266/Blink/Blink.ino.bin"
  skip_cleanup: true
  on:
    tags: true
```
It may be a good idea also to add a deploy demo configuration somewhere, maybe in the readme

### CODE REVIEW

**Comment by BenoitAnastay** [comment]
I removed path modification because of issue https://github.com/adafruit/travis-ci-arduino/issues/59
I don't see anything else that may cause an issue with my edits, everything is working properly on my repos

**Comment by ladyada** [comment]
hi we're not sure either but things were breaking meanwhile so we had to revert until we can spend more time looking

**Comment by BenoitAnastay** [comment]
@ladyada the https://github.com/adafruit/travis-ci-arduino/issues/59 issue is due to the fact that the commands aren't sourced and the .travis file wasn't updated

I'll try to fix that

**Comment by ladyada** [comment]
ok! thanks :)

**Comment by BenoitAnastay** [comment]
It should be fixed, after reverting `.travis.yml` it reproduced https://github.com/adafruit/travis-ci-arduino/issues/59 (https://travis-ci.com/adafruit/travis-ci-arduino/builds/141323655)

But with https://github.com/adafruit/travis-ci-arduino/pull/61/commits/8f87204e04c6968e3e9562a0c9545a14ba961e5e i can call those functions either as a command and as argument

**Comment by BenoitAnastay** [comment]
@ladyada 
You can security merge it now 
When you asked me to merge build.sh and install.sh I forgot that install.sh was sourcing commands for travis, sorry

**Comment by ladyada** [comment]
@makermelissa wanna test this tomrorow after mergin?

**Comment by BenoitAnastay** [comment]
A possible issue with the directory change is that it allow travis to deploy but will require a .gitignore but it's not the only things that generating files in the repository there is also Adafruit_Test_Library

**Comment by makermelissa** [comment]
@ladyada, sounds good. @BenoitAnastay, most repos have a.gitignore already.

**Comment by makermelissa** [comment]
I'm temporarily pointing a PR to BenoitAnastay's repo, so I can test it prior to merging. So far, so good. If that tests good, I'll merge and update my other PR.

**Comment by makermelissa** [comment]
It seemed to work great. Now to give it a live test.

**Comment by makermelissa** [comment]
Tested good live.

**Pull request merged**
