### PR TITLE
Upgrade to 1.8.3

### PR DESCRIPTION
**Pull request by Natim**
Upgrade to Arduino 1.8.3

### CODE REVIEW

**Comment by moritz89** [comment]
Since it is not merged yet, might it make sense to got straight to 1.8.5?

**Comment by ladyada** [comment]
bumped to 1.8.5 thanks!

**Comment by Natim** [comment]
@ladyada I wish you'd merge my commit but thanks for the update anyway.

**Comment by ladyada** [comment]
hiya, we cannot merge your commit because that would bring us back to 1.8.3 from 1.8.5 :)

**Pull request closed without merging**
