### PR TITLE
Documentation patch to alert the user about certain pitfalls

### PR DESCRIPTION
**Pull request by leonardoInf**
I've previously created an issue, now I have added some information on how to  "fix" (avoid) it and how toinstall custom libraries which aren't hosted by arduino.

### CODE REVIEW

**Comment by ladyada** [comment]
hiya you can add documentation but don't change the examples we use for all our libraries by removing things that we use

**Comment by leonardoInf** [comment]
ok, I will revert the deletion of the entries. which I found to be unnecessary.

**Comment by ladyada** [comment]
ok this is resolve now, from that other PR? we dont want to delete anything in the examples

**Comment by leonardoInf** [comment]
feel free to close it.

**Pull request closed without merging**
