### PR TITLE
Version bump + note

### PR DESCRIPTION
**Pull request by CornyjK**
Bump version in ´install.sh´ and add a note about version variable.

@ladyada

### CODE REVIEW

**Comment by CornyjK** [comment]
@ladyada 
Sorry for getting offtopic, but I didn't find any direct way how to contact you or Adafruit. My question is simple: Could you assign someone to maintain your DHT library? I like your libraries, but the DHT one is abadonned, if you can't assign anyone from Adafruit, you might consider assigning someone from community, I'd do it, if you don't want me for any reasons, I am sure there are a lot of other people that would do it as well. Thanks for response.

**Comment by ladyada** [comment]
@CornyjK hiya which library?

**Comment by CornyjK** [comment]
@ladyada 
This one: https://github.com/adafruit/DHT-sensor-library

**Comment by ladyada** [comment]
ok! yes! if someone wants to pop in to help with it that would be awesome. the library does work but there's many edge cases that we haven't tested/verified. is this something you can help with?

**Comment by CornyjK** [comment]
@ladyada There are many pull requests which could be merged.

**Comment by ladyada** [comment]
yes! but before they can  be merged they have to be tested :D and we can't break any back compatibility - is there one in particular you need?

**Comment by ladyada** [comment]
hey @CornyjK we've noticed that caching breaks when we use it with 1.8.7 - a lot of "sam.h" not found errors :/ so we're reverting to 1.8.5

**Pull request merged**
