### PR TITLE
Add nrf5x to build platform

### PR DESCRIPTION
**Pull request by hathach**
@ladyada  for review

### CODE REVIEW

**Comment by ladyada** [comment]
you may want to add nrf as a test in this repo (it self-tests!)

**Comment by ladyada** [comment]
https://travis-ci.com/adafruit/travis-ci-arduino

**Comment by hathach** [comment]
ah thanks, I don't know it have self-test, will submit another PR for nrf5x self test :)

**Comment by hathach** [comment]
You're right, it failed the self test since nrf5x bsp use a specific version of gcc, I will do more testing

https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/master/platform.txt#L31

**Comment by hathach** [comment]
update: I fixed the compiler issue with self-test, but it need to wait until nrf52 bsp is released to submit PR. There is still a bit of work to do with nrf52 BSP to get it ready before release. Please be patient :)

**Comment by ladyada** [comment]
im patient :D tag me when ready and ill check it!

**Pull request merged**
