### PR TITLE
Add caching support

### PR DESCRIPTION
**Pull request by CornyjK**
I would like to know your opinion, in certain cases this does speed up significantly (after 2nd pass).

[Travis of my repo](https://travis-ci.org/CornyjK/travis-ci-arduino)

This PR:
 - Adds support for caching.
 - Makes X and their opposites colored.
 - Cleans-up some stuff.

### CODE REVIEW

**Comment by CornyjK** [comment]
Build without existing cache is broken, fix in progress (probably tomorrow).

**Comment by CornyjK** [comment]
Hmm, I am not sure why it does not use last commit, anyways, my [build](https://travis-ci.org/CornyjK/travis-ci-arduino/builds/401388580) passed.

Who's build | Time
------------ | -------------
Your | [5:18](https://travis-ci.org/adafruit/travis-ci-arduino/builds/394678001)
My 1st pass | around 6 mins
My 2nd pass | [2:18](https://travis-ci.org/CornyjK/travis-ci-arduino/builds/401388580)

Offcourse there are issues that come with this edit, eg. Arduino CLI does not have return code for "checking" platform library, so it returns error.

**Comment by CornyjK** [comment]
I should probably add script for upgrading Arduino IDE.

**Comment by CornyjK** [comment]
@ladyada
Could you tell me your opinion?

**Comment by ladyada** [comment]
please squash and make sure travis runs before we can take a look!

**Comment by CornyjK** [comment]
I am sure that [Travis runs](https://travis-ci.org/CornyjK/travis-ci-arduino), not sure why it does not work on PR.

Travis is tested in those scenerios:
- No cache available
- Content already precached
- Set different version of Arduino IDE (which can be now set directly from `.travis.yml`
- Updating of libraries was also tested and recaching them back

**Comment by ladyada** [comment]
not sure what it is either but it definitely isn't working
https://travis-ci.org/adafruit/travis-ci-arduino
looks like its testing every example (which we dont need, we normally just test the hello_world. and also it says
```The program 'arduino' is currently not installed. To run 'arduino' please ask your administrator to install the package 'arduino'```

**Comment by CornyjK** [comment]
Look at my build, everything is fine, hint would be appreciated. If you look more closely to log, you can see it is missing my changes entirely, nothing is colored, my extra echoes not echoed either.

Totally broken, I can't find change that would break PR builds. [My](https://travis-ci.org/CornyjK/travis-ci-arduino/builds/401893108) and [your](https://travis-ci.org/adafruit/travis-ci-arduino/builds/401893127) are totally different. It seems like it misses my `build.sh` entirely, but it uses my `.travis.yml`.

**Comment by CornyjK** [comment]
Didn't study it yet, but it seems like #24 had the same issue, but that was PR from person with R/W permissions and he merged it.

**Comment by ladyada** [comment]
ok @deanm1278 will take a look!

**Comment by deanm1278** [comment]
ok @CornyjK @ladyada I've fixed the issue and merged.
@CornyjK all .travis.yml files need to be updated now to use that cache section, correct?

**Comment by CornyjK** [comment]
Exactly, unfortunately there is no other way. But it will work without caching too... I probably figured out, why PRs are broken, I will try to fix that later.

Od: deanm1278
Odesláno:pondělí 9. července 2018 23:46
Komu: adafruit/travis-ci-arduino
Kopie: Kryštof Černý; Mention
Předmět: Re: [adafruit/travis-ci-arduino] Add caching support (#25)

ok @CornyjK @ladyada I've fixed the issue and merged.
@CornyjK all .travis.yml files need to be updated now to use that cache section, correct?

**Comment by ladyada** [comment]
thanks everyone!

**Pull request merged**
